### ISSUE TITLE
[Request] PyEveLiveDPS

### ISSUE THREAD

**Issue by superusercode** [lkhrs/eve-tools#5]
https://github.com/ArtificialQualia/PyEveLiveDPS "a live DPS calculator and grapher for EVE Online" and has 135 stars

has standalone exe at https://github.com/ArtificialQualia/PyEveLiveDPS/releases/download/v2.7.2/PELD-standalone-v2.7.2.exe

**Comment by lkhrs** [comment]
This is cool! Thanks for the suggestion @superusercode. I'll take a look at adding this.
