### ISSUE TITLE
[Request] Evernus

### ISSUE THREAD

**Issue by superusercode** [lkhrs/eve-tools#6]
https://github.com/slysmoke/evernus Up to date fork of evernus, eve market software with analysis

https://github.com/slysmoke/evernus/releases/download/V4.0/Evernus-4.0-win64.zip portable zip

**Comment by lkhrs** [comment]
Thanks for the suggestion @superusercode! I'll take a look at adding this.

Adding the forum topic for my reference (issues are closed): https://forums.eveonline.com/t/evernus-3-8-release-the-ultimate-market-tool/6031/775

**Comment by lkhrs** [comment]
Evernus does not have a portable release. Both .exe files linked on the release page start a custom installer.

Happy to revisit this if Evernus adds a portable version.
